### PR TITLE
Add failing test for #1093

### PR DESCRIPTION
**Pull request by cmfcmf**
This adds a failing test for the problem described in #1093.

### CODE REVIEW

**Comment by cmfcmf** [comment]
I've updated the test slightly to clarfiy what the actual issue is:
- If both slug handlers are used in conjunction, the slug update is inconsistent between database and the in-memory objects of the EntityManager. 
- Take the following example: 
  - You have a tree entity (say "Occupation") with a unique tree-handler-based slug.
    - This generates a slug like `web/developer/php` for a tree node with the title `php` whose parent has the title `developer` whose parent has the title `web`.
    - Now if you update the `web` or `developer` node, the slugs of all child nodes are correctly changed and updated. **This works.**
  - Each occupation has many persons with names and of course a slug using the relative slug handler.
    - The goal is to prepend the slug of the tree to the person's name. If a person has `php` as occupation, it's slug will be `web/developer/php/person-name`. **This works.**
    - Now if the name of the `php` node is changed to `python`, it does update the person's slug to `web/developer/python/person-name`. **This works.**
    - Now here comes the problem: If a parent node changes it's slug, the slug of our poor PHP developer remains unchanged. I.e. if `developer` changes to `enthusiast`, the slug of the `php` *node* is correctly updated to `web/enthusiast/php`. **But the slug of the *person* is not updated and remains `web/developer/php/person-name`.** However, as evil ( :smirk: ) as this library is, it **does** correctly update the slug of the in-memory objects of the EntityManager. So the objects in-memory differ from the actual objects inside the database! Here are the corresponding code snippets:

In-memory handling (notice that it uses preg_match to change all the objects with slugs starting with the changed slug):
```php
foreach ($uow->getIdentityMap() as $className => $objects) {
    // for inheritance mapped classes, only root is always in the identity map
    if ($className !== $mappedByConfig['useObjectClass']) {
        continue;
    }
    foreach ($objects as $object) {
        if (property_exists($object, '__isInitialized__') && !$object->__isInitialized__) {
            continue;
        }
        $oid = spl_object_hash($object);
        $objectSlug = $meta->getReflectionProperty($mappedByConfig['slug'])->getValue($object);
        if (preg_match("@^{$oldSlug}@smi", $objectSlug)) {
            $objectSlug = str_replace($oldSlug, $slug, $objectSlug);
            $meta->getReflectionProperty($mappedByConfig['slug'])->setValue($object, $objectSlug);
            $ea->setOriginalObjectProperty($uow, $oid, $mappedByConfig['slug'], $objectSlug);
        }
    }
}
```
Actual things which happen to the database:
```php
public function replaceInverseRelative($object, array $config, $target, $replacement)
{
    $em = $this->getObjectManager();
    $qb = $em->createQueryBuilder();
    $qb->update($config['useObjectClass'], 'rec')
        ->set('rec.'.$config['slug'], $qb->expr()->concat(
            $qb->expr()->literal($target),
            $qb->expr()->substring('rec.'.$config['slug'], strlen($replacement)+1)
        ))
        ->where('rec.'.$config['mappedBy'].' = :object')
    ;
    $q = $qb->getQuery();
    $q->setParameters(compact('object'));

    return $q->execute();
}
```

**Comment by l3pp4rd** [comment]
Well, happy that you provided these details, will have a look when possible.

**Comment by l3pp4rd** [comment]
not sure whether it is the best option, but before it was checking the occupation_id which was different for the person in interest since he had an occupation assigned which was inheriting the one modified.
So now it does where based on previous slug.

**Comment by cmfcmf** [comment]
Thank you, it's working :-)

**Pull request merged**
