### PR TITLE
2.4.x compatibility for PR#1631

### PR DESCRIPTION
**Pull request by vbartusevicius**
Added `attribute-overrides` compatibility to 2.4.x
More: https://github.com/Atlantic18/DoctrineExtensions/pull/1631

### CODE REVIEW

**Comment by vbartusevicius** [comment]
Hmm... @l3pp4rd - could You gime me some hint on why travis failed? Cannot see any problem in my changes...

**Comment by l3pp4rd** [comment]
phpunit new version was installed and has some deprecations. it is fixed in master, but not in this branch.

**Comment by vbartusevicius** [comment]
Ačiū :)

**Comment by l3pp4rd** [comment]
Prašom :)

**Pull request merged**
