### PR TITLE
[Tree] Prevent setting integer value (root id) on an associated root property

### PR DESCRIPTION
**Pull request by aramalipoor**

### CODE REVIEW

**Comment by l3pp4rd** [comment]
looks good, also there may be places in [repository](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Tree/Traits/Repository/ORM/NestedTreeRepositoryTrait.php)

**Comment by aramalipoor** [comment]
I don't see any special case in repository ;)

**Comment by l3pp4rd** [comment]
indeed, ok, will need to make another release..

**Comment by aramalipoor** [comment]
@l3pp4rd Yeah, thanks, that would be great :D

**Pull request merged**
