### PR TITLE
Update Closure.php

### PR DESCRIPTION
**Pull request by durich**
I was having an error when creating a new entity, it's was because the insert part is asumming the column_name is the same name of the entity field/property.

This extra get's the correct name

### CODE REVIEW

**Comment by l3pp4rd** [comment]
but you should probably remove the previous line, since it overwrites the variable.

**Comment by durich** [comment]
Hi, 

I didn't remove the previous because it is needed so my new line of code uses it for the last mapping.

I just used another variable name to avoid the override.




Ricardo

**Comment by l3pp4rd** [comment]
ah indeed, missed it :)

**Comment by l3pp4rd** [comment]
thanks

**Pull request merged**
