### PR TITLE
[Tree] Ability to create relation to root node

### PR DESCRIPTION
**Pull request by aramalipoor**
I'm not sure if this is the right way, but in SyliusTaxonomyBundle we need to create a relation to root node.

```xml
<many-to-one field="root" target-entity="AppBundle\Entity\Taxon">
  <join-column name="tree_root" referenced-column-name="id" nullable="true" />
  <gedmo:tree-root />
</many-to-one>
```

### CODE REVIEW

**Comment by l3pp4rd** [comment]
well, that is a great addition, thanks. could you also mention this in **doc/tree** also if you have a little more time for a unit test case, would be good to ensure stability.

**Comment by aramalipoor** [comment]
@l3pp4rd Done ;)

**Comment by l3pp4rd** [comment]
everything else looks awesome, great work ;)

**Comment by aramalipoor** [comment]
Oops sorry my bad :p Done ;)

**Comment by aramalipoor** [comment]
@l3pp4rd When will you release 2.4.12 ?

**Comment by l3pp4rd** [comment]
@aramalipoor it will go with **2.5.0** but probably it is worth to cherry pick it for 2.4 as well. I will check with a release when I can, should be tomorrow..

**Comment by aramalipoor** [comment]
@l3pp4rd Awesome, thanks.

**Comment by l3pp4rd** [comment]
2.4.11 was released with this change

**Comment by aramalipoor** [comment]
@l3pp4rd Boom! :tada: Perfect!!

**Comment by aramalipoor** [comment]
:( Seems like it wasn't that easy to do! We're seeing fails in Sylius tests, which is not covered in tests here. The problem is that Tree extension is setting `rootId` (int) on `root` property in various places (which is not right when root is an association) and this is causing Doctrine exceptions.

I'll try to understand how affected parts work and come up with a solution. Can you give me some directions around this issue?

**Comment by l3pp4rd** [comment]
I think in that case, we need to go through the source, and see where the rootId (int) is used explicitly and change query builder to use a root property value instead. that should solve the problem without much of the effort. If you won't be able to find all places involving this, I will help you with that later ;)

**Comment by aramalipoor** [comment]
@l3pp4rd I've prepared a PR on #1515

**Pull request merged**
