### PR TITLE
Feature/tree root

### PR DESCRIPTION
**Pull request by delboy1978uk**
image

Now I have set `@Gedmo\TreeRoot(identifierMethod="getMenu")`, so it can restrict and renumber by the rows with a menu_id of x (the real tree root, a row in another table).

After running the repository method `moveUp(7)` (the action movie category, in the above example, third out of 3 movie categories), instead of an exception being thrown, now we get:

image

### CODE REVIEW

**Comment by delboy1978uk** [comment]
Oh yeah, i also changed to PSR-4, and moved the source code to the `src/` folder standard, which won't affect anything :-)

**Comment by delboy1978uk** [comment]
I tidied up the pull request, code is back in the lib folder so you should be able to review changes easily now :-)

**Comment by l3pp4rd** [comment]
yes, I would not accept the `lib` to `src` change since that would involve BC breaks, since some mapping was directly referenced to directories on configuration for some projects.

could you also add a unit test for this new feature?

**Comment by delboy1978uk** [comment]
Yeah sure, I can't do it today, but I'll work on it and give you another shout. Regarding the lib folder, we are now on PSR-4 anyway 😃 (just not in `src/`)

**Comment by delboy1978uk** [comment]
Hi @l3pp4rd I have tested the new functionality and updated the `tree.md` docs :-)

**Comment by l3pp4rd** [comment]
thanks for all the effort, hope it will be useful for all users ;)

**Pull request merged**
