### PR TITLE
[Translatable] Added translation suport for Embedded entity with Doctrine 2.5

### PR DESCRIPTION
**Pull request by burci**
Added translation support for embedded entity http://doctrine-orm.readthedocs.org/en/latest/tutorials/embeddables.html

### CODE REVIEW

**Comment by burci** [comment]
The test are failing because @Doctrine\ORM\Mapping\Embedded will appear only with doctrine version 2.5. Should I chaneg the composer.json ?

**Comment by guilhermeaiolfi** [comment]
Does the other extensions work fine with Doctrine 2.5?

**Comment by burci** [comment]
The parts i use worked fine.

With the following composer change (doctrine/mongodb components still depends on 2.4 doctrine/common):

```
diff --git a/composer.json b/composer.json
index cb4936b..8b48ac8 100644
--- a/composer.json
+++ b/composer.json
@@ -40,11 +40,11 @@
     "require": {
         "php": ">=5.3.2",
         "behat/transliterator": "~1.0",
-        "doctrine/common": "~2.4"
+        "doctrine/common": "dev-master as 2.4.0"
     },
     "require-dev": {
-        "doctrine/mongodb-odm": ">=1.0.0-BETA11",
-        "doctrine/orm": "~2.4",
+        "doctrine/mongodb-odm": "dev-master",
+        "doctrine/orm": "dev-master",
         "symfony/yaml": "~2.3",
         "phpunit/phpunit": "~4.4",
         "phpunit/phpunit-mock-objects": "~2.3"
```

I got these errors only while running test:

```
PHPUnit 4.4.5 by Sebastian Bergmann.

Configuration read from vendor/gedmo/doctrine-extensions/tests/phpunit.xml.dist

........S......SS..FS...FSSSS..................................  63 / 416 ( 15%)
F.F...F.F.F.F......SS..SS........S...............SSS........... 126 / 416 ( 30%)
.............SSS..........................EEEEEEE....SSSSSSSSSS 189 / 416 ( 45%)
SS............................................................S 252 / 416 ( 60%)
SS.....SS........SS........SSS..........SS......SSSS........... 315 / 416 ( 75%)
.SS........SSSSS...........SSS................................. 378 / 416 ( 90%)
..............................SSSSSSSS

Time: 3.35 minutes, Memory: 96.75Mb

There were 7 errors:

1) Gedmo\Tree\ClosureTreeTest::testClosureTree
Doctrine\ORM\Mapping\MappingException: Entity 'Tree\Fixture\Closure\Person' has to be part of the discriminator map of 'Tree\Fixture\Closure\Person' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Tree\Fixture\Closure\Person' an abstract class to avoid this exception from occurring.

vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:679
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:338
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:80
vendor/gedmo/doctrine-extensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:69
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:70
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tree/ClosureTreeTest.php:43

2) Gedmo\Tree\ClosureTreeTest::testUpdateOfParent
Doctrine\ORM\Mapping\MappingException: Entity 'Tree\Fixture\Closure\Person' has to be part of the discriminator map of 'Tree\Fixture\Closure\Person' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Tree\Fixture\Closure\Person' an abstract class to avoid this exception from occurring.

vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:679
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:338
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:80
vendor/gedmo/doctrine-extensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:69
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:70
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tree/ClosureTreeTest.php:43

3) Gedmo\Tree\ClosureTreeTest::testAnotherUpdateOfParent
Doctrine\ORM\Mapping\MappingException: Entity 'Tree\Fixture\Closure\Person' has to be part of the discriminator map of 'Tree\Fixture\Closure\Person' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Tree\Fixture\Closure\Person' an abstract class to avoid this exception from occurring.

vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:679
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:338
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:80
vendor/gedmo/doctrine-extensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:69
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:70
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tree/ClosureTreeTest.php:43

4) Gedmo\Tree\ClosureTreeTest::testBranchRemoval
Doctrine\ORM\Mapping\MappingException: Entity 'Tree\Fixture\Closure\Person' has to be part of the discriminator map of 'Tree\Fixture\Closure\Person' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Tree\Fixture\Closure\Person' an abstract class to avoid this exception from occurring.

vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:679
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:338
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:80
vendor/gedmo/doctrine-extensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:69
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:70
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tree/ClosureTreeTest.php:43

5) Gedmo\Tree\ClosureTreeTest::testSettingParentToChild
Doctrine\ORM\Mapping\MappingException: Entity 'Tree\Fixture\Closure\Person' has to be part of the discriminator map of 'Tree\Fixture\Closure\Person' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Tree\Fixture\Closure\Person' an abstract class to avoid this exception from occurring.

vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:679
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:338
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:80
vendor/gedmo/doctrine-extensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:69
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:70
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tree/ClosureTreeTest.php:43

6) Gedmo\Tree\ClosureTreeTest::testIfEntityHasNotIncludedTreeLevelFieldThenDontProcessIt
Doctrine\ORM\Mapping\MappingException: Entity 'Tree\Fixture\Closure\Person' has to be part of the discriminator map of 'Tree\Fixture\Closure\Person' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Tree\Fixture\Closure\Person' an abstract class to avoid this exception from occurring.

vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:679
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:338
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:80
vendor/gedmo/doctrine-extensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:69
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:70
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tree/ClosureTreeTest.php:43

7) Gedmo\Tree\ClosureTreeTest::testCascadePersistTree
Doctrine\ORM\Mapping\MappingException: Entity 'Tree\Fixture\Closure\Person' has to be part of the discriminator map of 'Tree\Fixture\Closure\Person' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Tree\Fixture\Closure\Person' an abstract class to avoid this exception from occurring.

vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:679
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:338
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:80
vendor/gedmo/doctrine-extensions/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:225
vendor/gedmo/doctrine-extensions/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:69
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tool/BaseTestCaseORM.php:70
vendor/gedmo/doctrine-extensions/tests/Gedmo/Tree/ClosureTreeTest.php:43

--

There were 8 failures:

1) Gedmo\Translatable\PersonalTranslationTest::shouldTranslateTheRecord
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'SELECT t0.id AS id1, t0.locale AS locale2, t0.field AS field3, t0.content AS content4, t0.object_id AS object_id5 FROM article_translations t0 WHERE t0.object_id = 1'
+'SELECT t0.id AS id_1, t0.locale AS locale_2, t0.field AS field_3, t0.content AS content_4, t0.object_id AS object_id_5 FROM article_translations t0 WHERE t0.object_id = 1'

vendor/gedmo/doctrine-extensions/tests/Gedmo/Translatable/PersonalTranslationTest.php:84

2) Gedmo\Translatable\PersonalTranslationTest::shouldBeAbleToUseTranslationQueryHint
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'SELECT CAST(t1_.content AS VARCHAR(128)) AS title0 FROM Article a0_ LEFT JOIN article_translations t1_ ON t1_.locale = 'lt' AND t1_.field = 'title' AND t1_.object_id = a0_.id'
+'SELECT CAST(t1_.content AS VARCHAR(128)) AS title_0 FROM Article a0_ LEFT JOIN article_translations t1_ ON t1_.locale = 'lt' AND t1_.field = 'title' AND t1_.object_id = a0_.id'

vendor/gedmo/doctrine-extensions/tests/Gedmo/Translatable/PersonalTranslationTest.php:219

3) Gedmo\Translatable\TranslationQueryWalkerTest::testSelectWithTranslationFallbackOnSimpleObjectHydration
Failed asserting that 2 matches expected 1.

gedmo/doctrine-extensions/tests/Gedmo/Translatable/TranslationQueryWalkerTest.php:150

4) Gedmo\Translatable\TranslationQueryWalkerTest::testSelectWithOptionalFallbackOnSimpleObjectHydration
Failed asserting that 2 matches expected 1.

vendor/gedmo/doctrine-extensions/tests/Gedmo/Translatable/TranslationQueryWalkerTest.php:208

5) Gedmo\Translatable\TranslationQueryWalkerTest::testSelectWithTranslationFallbackOnObjectHydration
Failed asserting that 2 matches expected 1.

vendor/gedmo/doctrine-extensions/tests/Gedmo/Translatable/TranslationQueryWalkerTest.php:308

6) Gedmo\Translatable\TranslationQueryWalkerTest::testSelectOrderedJoinedComponentTranslation
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Alfabetas'
+'Alfabet'

vendor/gedmo/doctrine-extensions/tests/Gedmo/Translatable/TranslationQueryWalkerTest.php:407

7) Gedmo\Translatable\TranslationQueryWalkerTest::testSelectSecondJoinedComponentTranslation
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Maistas'
+'Food'

vendor/gedmo/doctrine-extensions/tests/Gedmo/Translatable/TranslationQueryWalkerTest.php:517

8) Gedmo\Translatable\TranslationQueryWalkerTest::testSelectSingleComponentTranslation
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Maistas'
+'Food'

vendor/gedmo/doctrine-extensions/tests/Gedmo/Translatable/TranslationQueryWalkerTest.php:614
                                                                  
FAILURES!                                                         
Tests: 416, Assertions: 2345, Failures: 8, Errors: 7, Skipped: 65.
```

I can look after this erros, but i don't know, against which branch should i make my pull request.

**Comment by guilhermeaiolfi** [comment]
Nice report. It seems the only affected extension is the Translatable and Tree. Those errors in the Tree I had in my project too. I think they make sense and it's pretty easy to fix. I would say that if the changes are backwards compatible it should go into master. But I don't know, I just started using doctrine recently. Thank your for your effort on this.

**Comment by burci** [comment]
After mergin the master with 2.5 upgrades, the test works fine.

**Comment by l3pp4rd** [comment]
is it working with query hints? will need to test that next week, don't want to merge partially working features

**Comment by burci** [comment]
I added now a test for query walker as well.

**Comment by burci** [comment]
@l3pp4rd is there anything else I should test?

**Comment by l3pp4rd** [comment]
ok, thanks ;)

**Pull request merged**
