### PR TITLE
Support for versioning of @EmbedMany ODM relations

### PR DESCRIPTION
**Pull request by kl4n4**
Big thanks goes to @Engerim since the core functionality of this implementation is based on his work in https://github.com/Engerim/DoctrineExtensions/commit/079e8326ac032cdb024 
Additionally the revert functionality was adapted to support these kind of relations and the listing of log entries for an object can now be paged using optional _limit_ and _skip_ parameters

closes #1069 
closes #1260

### CODE REVIEW

**Comment by kl4n4** [comment]
this PR should render #1069 and #1260 redundant and out-of-date

**Comment by l3pp4rd** [comment]
fantastic, thanks !

**Comment by carlos-granados** [comment]
Why has this not been released in any of the stable branches. This was done 2 years ago!!

**Comment by l3pp4rd** [comment]
Hi, the master branch was expected for major version change to 3.0.0. but it was cancelled. the patch can be migrated to v2.4.x

**Comment by carlos-granados** [comment]
I found an issue with this code, I have created a pull request to fix it https://github.com/Atlantic18/DoctrineExtensions/pull/1924

**Comment by markitosgv** [comment]
What about merging this in 2.4.x ? I'm using embedMany objects that I want to log. Thanks!

**Comment by mustanggb** [comment]
This is not included in the latest release (v3.15.0) so still needs porting/rerolling.

**Comment by mustanggb** [comment]
Trying a new port #2791.

**Pull request merged**
