### PR TITLE
[Tree] Introduce tree repository traits and remove abstract tree repositories

### PR DESCRIPTION
**Pull request by aramalipoor**
@l3pp4rd Regarding #1493 do you think this is a good start?

### CODE REVIEW

**Comment by lrlopez** [comment]
Cool! I was going to propose a PR extending trait support to closure trees and just found this. :+1:

**Comment by l3pp4rd** [comment]
@aramalipoor yes it is still a good idea, but we need to leave NestedTreeRepository as a class which uses NestedTreeRepositoryTrait, this would ensure backward compatibility if php 5.4 or higher is used. I will bump minor version to 2.5 but still, I do not want to break BC that much. Also lets name traits ending with **Trait** it conforms [psr](https://github.com/php-fig/fig-standards/blob/master/bylaws/002-psr-naming-conventions.md) and I do not want to fight with @stof :) even if I do not like the naming. @lrlopez your PR as merged, this one may take longer and should be rebased if needed.

**Comment by aramalipoor** [comment]
@l3pp4rd You're right, I've reverted Abstract repositories so no BC ;) Anything else to correct/add?

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by l3pp4rd** [comment]
great, thanks

**Pull request merged**
