### PR TITLE
Making desactivation of soft deletable working

### PR DESCRIPTION
**Pull request by sylvaincombes**
This patch make sure that the filter is enabled in the onFlush event before applying the behavior.

I experienced malfunction of this behavior, when I did something like that : 

```
    $em->getFilters()->disable('softdeleteable');
    $product = $em->getRepository('AppBundle:Product')->findOneBy(['idWorldwide' => 'XSWQAZ']);
    $em->remove($product);
    $em->flush();
```

It doesn't work the soft deletable behavior is still applied, this patch correct this.

### CODE REVIEW

**Comment by l3pp4rd** [comment]
I think it would be easier to detach listener from event manager. it would be compatible with both, orm and odm

**Comment by sylvaincombes** [comment]
Hi @l3pp4rd thanks for your work, I don't understand what you mean in your comment can you give me some hint on what you are expecting so I can try to do it ?

The patch seems to work : https://travis-ci.org/Atlantic18/DoctrineExtensions/jobs/95424505 
The failed one are likely due to misconfiguration, see https://travis-ci.org/Atlantic18/DoctrineExtensions/jobs/95424506 for example.

**Comment by l3pp4rd** [comment]
I meant that to disable softdeleatable, you can create a [method like this](http://stackoverflow.com/questions/12738974/remove-doctrine-life-cycle-event-from-within-a-symfony2-controller/12747541#12747541) to switch it on or off based on your needs.

**Comment by AkenRoberts** [comment]
Hello, and thank you for your contribution.

In the interest of spring cleaning and package modernization, I'm going through and closing old issues and pull requests that have had no recent activity, do not have associated tests, or have failing tests.

If you are still experiencing this issue or wish to contribute an up-to-date pull request, please create a new issue.

Thank you!

**Pull request closed without merging**
