### PR TITLE
Sluggable with embeddable

### PR DESCRIPTION
**Pull request by TNAJanssen**

### CODE REVIEW

**Comment by l3pp4rd** [comment]
if it supports only php 7, that cannot be accepted. try to find the reasons why this property is not available in older versions

**Comment by TNAJanssen** [comment]
@l3pp4rd  it's weird that for some reason the error isn't on PHP7.0! Maybe that one doesn't have mongoDB? I should have fixed it right now for PHP5

**Comment by garak** [comment]
I'd love to see this PR merged.

**Comment by AkenRoberts** [comment]
Hello, and thank you for your contribution.

In the interest of spring cleaning and package modernization, I'm going through and closing old issues and pull requests that have had no recent activity, do not have associated tests, or have failing tests.

If you are still experiencing this issue or wish to contribute an up-to-date pull request, please create a new issue.

Thank you!

**Pull request closed without merging**
