### PR TITLE
Add an option to enable/disable hard delete

### PR DESCRIPTION
**Pull request by babeou**
Soft delete works like this:
- first call: it sets the fieldname with a new DateTime
- second call: it hard deletes your record

## Problem
I'd like to be able to disable the hard delete but there's no configuration to do it.

## Solution
I suggest to add a parameter in order to disable the hard delete.
By default I let the hardDelete parameter to true in order to keep the default behaviour.

Hope you'll like it.

### CODE REVIEW

**Comment by l3pp4rd** [comment]
Hello, thank you, would you be able to add the [documentation](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/softdeleteable.md) for this new option?

**Comment by babeou** [comment]
You've right, that's done!

**Comment by l3pp4rd** [comment]
thanks, that is a nice fluent contribution ;)

**Comment by enricog84** [comment]
@babeou it seems that this PR introduced a bc break, see #1864

**Pull request merged**
