### PR TITLE
Fix DoctrineExtensions for latest ODM

### PR DESCRIPTION
**Pull request by malarzm**
Since we have removed `scheduleExtraUpdate` in latest ODM few extensions stopped working. Affected are

- [x] Loggable
- [x] SoftDeleteable
- [ ] Tree

@l3pp4rd I'm not sure when I'll be able to work on Tree extension, possibly good idea would be to merge this PR and leave fixing Tree to somebody else/future me

### CODE REVIEW

**Comment by malarzm** [comment]
Eh turns out that my fixes require latest ODM and are failing on BETA-13

**Comment by l3pp4rd** [comment]
thanks for the initial fixes @malarzm but the tests would fail either way, will try to fix the tree

**Comment by l3pp4rd** [comment]
had to skip materialized path locking test for odm, not sure what is missing there, but hope people will be able to resolve that in case if needed

**Comment by malarzm** [comment]
:+1:

**Pull request merged**
