### PR TITLE
[ReferenceIntegrity] Tests and doc to the new 'pull' feature.

### PR DESCRIPTION
**Pull request by Alsatian67**
I have added two tests.
+ changes in the ReferenceIntegrity documentation

### CODE REVIEW

**Comment by Alsatian67** [comment]
Documentation and Tests for #1362

**Comment by l3pp4rd** [comment]
good work, thanks!

**Comment by Alsatian67** [comment]
@l3pp4rd can I integrate that on older branches ? I don't know how it works and what is you politic for new features.

But the 2.4 version cannot be used in symfony due to that :
https://github.com/stof/StofDoctrineExtensionsBundle/issues/278

**Comment by l3pp4rd** [comment]
hi, with symfony I would recommend to use extensions with a [manual configuration settings](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/symfony2.md) it allows more flexibility and listener service access and is fairly simple to integrate

**Comment by l3pp4rd** [comment]
concerning other branches, only the **master** is active and no other branches are used by anybody. so there is no need to backport anything

**Pull request merged**
