### PR TITLE
Add doctrine/commons 3.0 support

### PR DESCRIPTION
**Pull request by svycka**
let us see what will happen with tests

### CODE REVIEW

**Comment by svycka** [comment]
okay, I guess it's not possible to support PHP 5.x and doctrine/commons 3.0. Just wondering do we have users who need support for PHP 5.x versions? Even if they use it I guess they do not plan to update this lib also.

**Comment by sixpeteunder** [comment]
I don't know if this is relevant, but as per the doctrine/orm page on Packagist, they only have support for PHP 7.1 from [2.6.0](https://packagist.org/packages/doctrine/orm#v2.6.0) onwards. 

The [latest version, 2.7.3](https://packagist.org/packages/doctrine/orm#v2.7.3), installs doctrine/common 3.0 by default, and the [2.8.x-dev branch](https://packagist.org/packages/doctrine/orm#2.8.x-dev) has support for 3.0 only.

Again, I'm not sure this is relevant, and it's far from a professional opinion. Just sharing this in the hopes of providing insight on what the doctrine community looks like.

**Comment by svycka** [comment]
we just have to drop <=7.1 PHP versions if we want to get the latest doctrine packages there is no other way and I don't think this is a bad thing. Why we need to support EOL versions of PHP.
@AkenRoberts maybe we can vote for this?

**Comment by jaikdean** [comment]
@svycka I agree. Prioritising support for EOL versions of PHP over current versions of package dependencies doesn't make sense.

**Comment by AkenRoberts** [comment]
I'm remote right now, but check `master`, this may have been done there already.

One of the goals there was to bump dependencies and prepare for more modern usage.

2.4.x is essentially deprecated, with only basic bug fixes being applied.

**Comment by AkenRoberts** [comment]
I appreciate the insights and whatnot shared here.

Just to confirm that nothing like this is happening on 2.4.x. So closing mostly because of that.

See #2130 for some general discussion on supporting `doctrine/common` 3.0, and #2159 for an implementation. 👍

**Pull request closed without merging**
