### PR TITLE
Fix translatable

### LINKED ISSUE #2152: Translatable doesn't fallback if translations are null
In our system we're using a2lix/translation-form-bundle for managing translations. And this bundle saves missing translations as null. Expected behavior will be that for missing translations it should fallback to default locale.

But after #1709 it's no longer the case: null considered as valid translation now.

### PR DESCRIPTION
**Pull request by mente**
Resolves #2152 while keeping behavior described in #1709

### CODE REVIEW

**Comment by mente** [comment]
I'm sorry, I was targeting master first and it required 7.2, now I check 2.4.x branch and it looks like 5.3 is minimum dependency. While change in class itself is no problem, tests are obviously not 5.3 friendly. Will fix it

**Comment by mente** [comment]
Great, now works :). I can also provide separate PR for master branch if you find this valuable

**Comment by AkenRoberts** [comment]
Much obliged. 🥇

**Comment by AkenRoberts** [comment]
No worries on the separate PR, I'll get it merged upstream. The tests in general need a ton of updating, so no sense in having one perfect one. 😂

**Pull request merged**
