### PR TITLE
Allow to configure hard deletion

### PR DESCRIPTION
**Pull request by becoded**
Allow to configure hard deletion.
By default, hard deletion is active to be backwards compatible.

### CODE REVIEW

**Comment by l3pp4rd** [comment]
Hi, what is exactly about? can you explain what this feature adds and why it is needed?

**Comment by becoded** [comment]
Hi,
This is related with the current behaviour of softDeletable entities.
The first time you delete an entity, it will be soft deleted, meaning, the _delete_at_ will be filled in.
If you have a soft deleted entity and you remove it again, it will be hard deleted.

Or in code: 
```
$user = $repo->findOneBy(array('username' => $username));
$this->em->remove($user);
$this->em->flush();
// Entity is soft deleted at this point. (deleted_at field is filled in)
$this->em->remove($user);
$this->em->flush();
// Entity is hard deleted => removed from the database at this point.
```

The added options makes it possible to disable hard deletion so you are sure your entities are never deleted from the database. 
```
// with allowHardDelete=false
$user = $repo->findOneBy(array('username' => $username));
$this->em->remove($user);
$this->em->flush();
// Entity is soft deleted at this point. (deleted_at field is filled in)
$this->em->remove($user);
$this->em->flush();
// Entity is still soft deleted
```

**Comment by l3pp4rd** [comment]
well, I do not want to add extra options just in order to add them. it confuses people. because in order to prevent hard deletion, check the `deletedAt` field whether it is null or not. if you do want to auto check that, create an event listener which would not propagate deletion at all, if that field is not null. If you can do it one or another way without that option, do not create such an option.

**Comment by becoded** [comment]
Thanks @l3pp4rd for your answer.
I didn't add this option, just to add it of course. A customer has a huge codebase and for certain flows, soft-deleted entities needs to be included.
To avoid losing any data, they forked this repo and removed the lines where the hard-deletion is done.
I added this flag in an effort to use the main-repos instead of some outdated forks and I also wanted to share it with the community.

It made sense to me to have soft-deletion doing just soft-deletion and not switch suddenly to hard-deletion (as far as I can see, this behaviour isn't documented btw).
As it wasn't the case and I didn't want to break implementations that relies on this, I added the option.

Thanks for the suggestions btw, but I believe that you will have issues with cascades.

**Comment by l3pp4rd** [comment]
I think hardDelete option was added to replace this, should be resolved ;)

**Comment by becoded** [comment]
I'm glad you changed your mind in the end!

**Comment by l3pp4rd** [comment]
well, indeed, made a mistake, anyway glad someone else went the same way to revisit it ;) and it made me think twice, since more users needed such behavior

**Pull request closed without merging**
