### PR TITLE
Fixed ODM adapter for Sluggable unique_base

### PR DESCRIPTION
**Pull request by attilabukor**

### CODE REVIEW

**Comment by biiccs** [comment]
I also need this fix.

**Comment by l3pp4rd** [comment]
there are conflicts, have you rebased or maybe you wanted to PR on v2.4.x branch

**Comment by r1pp3rj4ck** [comment]
Gonna rebase sometime next week when I'm back to work.

**Comment by AkenRoberts** [comment]
Hello, and thank you for your contribution.

In the interest of spring cleaning and package modernization, I'm going through and closing old issues and pull requests that have had no recent activity, do not have associated tests, or have failing tests.

If you are still experiencing this issue or wish to contribute an up-to-date pull request, please create a new issue.

Thank you!

**Pull request closed without merging**
