### PR TITLE
Add documentation links to extension summary

### PR DESCRIPTION
**Pull request by Rvanlaak**

### CODE REVIEW

**Comment by Rvanlaak** [comment]
ping @l3pp4rd

**Comment by l3pp4rd** [comment]
very good idea, thanks, could you rebase? sorry for the late response

**Comment by Rvanlaak** [comment]
done :+1:

**Comment by l3pp4rd** [comment]
thanks ;)

**Comment by Rvanlaak** [comment]
No problem, time for a new release soon?

**Comment by l3pp4rd** [comment]
just made one ;)

**Pull request merged**
