### PR TITLE
[Loggable] ODM query performance fix using compound index

### PR DESCRIPTION
**Pull request by robholmes**
Adds a compound index to ODM `LogEntry`, to optimise query performance, especially for `getNewVersion` query.

Fixes https://github.com/Atlantic18/DoctrineExtensions/issues/1811

### CODE REVIEW

**Comment by l3pp4rd** [comment]
Hi please add index not to the mapped superclass but to the LogEntry class, because the superclass is meant to be used with customizations including indexes.

**Comment by robholmes** [comment]
Hi @l3pp4rd, I am unsure about the reason for moving it, as for ODM all other indexes are clearly defined in the `AbstractLogEntry` class (`MappedSuperclass`).

I'm not sure it makes sense to put just one of the 
core indexes in the `LogEntry` class, doesn't it make sense to keep these together?

**Comment by l3pp4rd** [comment]
https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Loggable/Document/LogEntry.php

has no indexes, so instead of superclass, place index to this class. the point is to have it overridable. same as for example translatable https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Translatable/Document/Translation.php has indexes in this instead of mapped superclass.

**Comment by robholmes** [comment]
@l3pp4rd I see what you mean now, I have fixed this and moved all index definitions from the MappedSuperclass to the `LogEntry` class.

**Comment by l3pp4rd** [comment]
thanks ;)

**Comment by robholmes** [comment]
@l3pp4rd no problem, just glad I could contribute :+1:

**Pull request merged**
