### PR TITLE
Add support for empty root nodes in MaterializedPath strategy

### PR DESCRIPTION
**Pull request by BowlingX**
Right now, `MaterializedPath` does not support empty root nodes.
I added support for empty `titles` that also play correctly with other configuration options like `path_starts_with_separator` etc.

This is work in progress, I will add more tests to cover other configurations.

### CODE REVIEW

**Comment by l3pp4rd** [comment]
this is a big change, what do you mean by empty root nodes, if a node path element is empty, that does not make any sense. the path would simply not be valid, for example a child node could match the same root/child node.

**Comment by BowlingX** [comment]
Right now it is not possible / buggy to have a node that has an empty name and has no parent id (what yields to an empty path). I also introduced support for `path_starts_with_separator`, so we can have a real root node in this strategy. (/).

**Comment by l3pp4rd** [comment]
No, no, I cannot accept such feature, extensions are currently locked for new features (including new options) unless they are really necessary. But in your case, empty path nodes could lead to much more trouble and confusion for every user who may interact with it. I suggest you to prevent such tree paths or use NestedSet instead, you can also base your path on Node ID, and build path in separate repository method based on titles (which may be empty in your case). But this is not something I would want to include in the library at all.

**Comment by BowlingX** [comment]
I understand. But `NestedSet` supports the same behaviour and MaterializedPath is broken in this case. This is not really a new feature but a bugfix. I will provide an example. This should also not break existing implementations.

**Comment by l3pp4rd** [comment]
nested set does not depend on titles and for that reason it cannot be broken. if you use empty titles for a tree path I think that is your problem, unless I do not understand something. Please explain how you are trying to fix it?

**Comment by AkenRoberts** [comment]
Hello, and thank you for your contribution.

In the interest of spring cleaning and package modernization, I'm going through and closing old issues and pull requests that have had no recent activity, do not have associated tests, or have failing tests.

If you are still experiencing this issue or wish to contribute an up-to-date pull request, please create a new issue.

Thank you!

**Pull request closed without merging**
