### PR TITLE
Improved Reference extension

### PR DESCRIPTION
**Pull request by dbojdo**

### CODE REVIEW

**Comment by l3pp4rd** [comment]
could you add a reference test to prevent regression?

**Comment by dbojdo** [comment]
Test is already there. See: https://github.com/dbojdo/DoctrineExtensions/commit/54b19d5410063f6a62cce8f3b98e49cdfb015579#diff-69d5143cc504ebc2545a7dd48968cd34

Or do you mean the other kind of tests?

**Comment by l3pp4rd** [comment]
ah, missed that it has changed to registries, will that is backward incompatible change. will need to delay it till 2.5 version

**Comment by prolic** [comment]
This PR is kind of old already. Any reason why it's not merged, yet?

**Comment by l3pp4rd** [comment]
it is backward incompatible. I doubt that extensions will make any BC changes, it will stay stable

**Comment by AkenRoberts** [comment]
Hello, and thank you for your contribution.

In the interest of spring cleaning and package modernization, I'm going through and closing old issues and pull requests that have had no recent activity, do not have associated tests, or have failing tests.

If you are still experiencing this issue or wish to contribute an up-to-date pull request, please create a new issue.

Thank you!

**Pull request closed without merging**
