### PR TITLE
Multiple sortable fields

### PR DESCRIPTION
**Pull request by Padam87**
- [x] Old test pass with new config
- [x] Test multiple sortables on one object
- [x] Test multiple sortables with a group mutually used
- [x] Update xml and yaml drivers
- [x] Update docs and changelog
- [x] need to update [xsd schema](https://github.com/Atlantic18/DoctrineExtensions/blob/master/schemas/orm/doctrine-extensions-mapping-2-2.xsd) and I need to host it somewhere else, github page would be best

### CODE REVIEW

**Comment by Padam87** [comment]
@l3pp4rd I think that apart from documenting the BC break, it is ready.

**Comment by l3pp4rd** [comment]
well, you did a great job, that was something. I'll review and document it in few days (I'm not that fast)..

**Comment by Padam87** [comment]
Thanks :)

**Comment by l3pp4rd** [comment]
I see there is some formatting incompatibility, make sure you use spaces instead of tabs for indentation.

**Comment by Padam87** [comment]
Those issues are caused by the whole block moving a level deeper.

Insted of getting the configuration, now it iterates over the sortables:
`foreach ($config['sortables'] as $config) {`

It makes it horrible to read...

**Comment by l3pp4rd** [comment]
ah OK, anyway will check it next day, cheers ;)

**Comment by Padam87** [comment]
Should I create a new `doctrine-extensions-mapping-3-0.xsd` ?

**Comment by l3pp4rd** [comment]
amazing work ;)

**Comment by stof** [comment]
doing a BC break in the 2.4.14 release is a bad idea

**Comment by Padam87** [comment]
@stof Yep, looks like the 2.4.14 release accidentally referenced the master branch (3.0).

https://github.com/Atlantic18/DoctrineExtensions/issues/1624

**Comment by l3pp4rd** [comment]
ups, will need to retag

**Comment by hafkenscheid** [comment]
Seems that this PR is not in master, nor 3.0.0 beta anymore. Is there any reason for that?

**Comment by svycka** [comment]
@hafkenscheid I think https://github.com/Atlantic18/DoctrineExtensions/issues/2162 can be related

**Comment by AkenRoberts** [comment]
This was merged into a previous version of `master` and 3.0, which had a ton of diverging changes but was never made stable. Because of the maintainer switch and no one with historical knowledge of all the changes, `master` was archived at [`archive/master-2019-03-17`](https://github.com/Atlantic18/DoctrineExtensions/tree/archive/master-2019-03-17).

`master` is now a new 3.0, with a refocus on more simple updates on dependencies.

**Pull request merged**
