### PR TITLE
[Tree] Add method(removeFromTree) to repository for delete node.

### PR DESCRIPTION
**Pull request by nirav-programmer**

### CODE REVIEW

**Comment by l3pp4rd** [comment]
Hi, could you also add a test to prevent regressions in future?

**Comment by nirav-programmer** [comment]
Yes, sure.

**Comment by nirav-programmer** [comment]
@l3pp4rd Test case implemented.

**Comment by l3pp4rd** [comment]
it seems there are conflicts, are you targeting master branch?

**Comment by nirav-programmer** [comment]
Yes, changes pushed to master branch.
I can't found any conflicts.

Please correct me if I am wrong.

**Comment by l3pp4rd** [comment]
I cannot merge the PR because it has merge conflicts, can you make a rebase on upstream master?

**Comment by nirav-programmer** [comment]
Done.

**Comment by l3pp4rd** [comment]
great, thanks

**Comment by l3pp4rd** [comment]
ah, you made a merge commit
do `git pull --rebase upstream master`

**Comment by l3pp4rd** [comment]
see https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by nirav-programmer** [comment]
@l3pp4rd Done

**Pull request merged**
