### PR TITLE
Add loggable support for embedded entities introduced by doctrine >=2.5

### PR DESCRIPTION
**Pull request by fabsb**
relates to #1309

### CODE REVIEW

**Comment by l3pp4rd** [comment]
great, could you also update https://github.com/Atlantic18/DoctrineExtensions/blob/master/schemas/orm/doctrine-extensions-mapping-2-2.xsd it may not pass xsd validation now

**Comment by fabsb** [comment]
@l3pp4rd I made another PR for doctrine2 as it is an issue on their side for not allowing other namespaced tags or attributes for the embedded tag. I hope the PR gets through and the schema deployed soon.

**Comment by l3pp4rd** [comment]
ok, thanks ;)

**Comment by Ocramius** [comment]
Just pinging back here: doctrine/doctrine2#1488 was closed - I think we should move forward to splitting mapping files, rather than mixing them together.

**Comment by cordoval** [comment]
@fabsb do you think you can do the mapping file splitting as @Ocramius suggested? I am duplicating my columns just because of this:

```php
<?php

public function setPatientInformation(PatientInformation $patientInformation)
    {
        $this->patientInformation = $patientInformation;

        $this->updateAddress();

        return $this;
    }

private function updateAddress()
    {
        $this->address1 = $this->patientInformation->getAddress()->getAddress1();
        $this->address2 = $this->patientInformation->getAddress()->getAddress2();
        $this->city = $this->patientInformation->getAddress()->getCity();
        $this->state = $this->patientInformation->getAddress()->getState();
        $this->county = $this->patientInformation->getAddress()->getCounty();
        $this->zipcode = $this->patientInformation->getAddress()->getZipcode();
    }
}
```

Thanks 😊

**Comment by fabsb** [comment]
@cordoval I don't see how separating the extension mappings from the doctrine mapping files would help you with your issue.

**Comment by cordoval** [comment]
I doesn't help it, all i want is just to use the feature. But i can't it seems. In any case I have resolved the problem another way, different from the one above.

**Comment by fabsb** [comment]
Well you could use the feature as it is now without separating the mappings for the extension as I have used it in other projects of mine.

@l3pp4rd If you want I could work on separating the mapping as suggested but note that it would break BC so maybe for 2.5 or 2.6?

**Comment by cordoval** [comment]
weird, i did try, was using yaml though so not sure why it did not work for me.

**Comment by l3pp4rd** [comment]
@fabsb BC break is allowed in master 3.0.0, but have to add reference in [upgrade guide](https://github.com/Atlantic18/DoctrineExtensions/blob/master/UPGRADE-3.0.md) so if you could make a PR you are welcome.

**Pull request merged**
